import type { Category, Collection, Product, WholesaleTier } from "@/lib/types";

/**
 * ÖRNEK VERİ — gerçek ürün kataloğu gelince bu dosya
 * bir CMS / veritabanı / ERP entegrasyonu ile değiştirilecek.
 * Arayüz (lib/catalog/index.ts) aynı kaldıkça sayfalar etkilenmez.
 */

export const categories: Category[] = [
  { slug: "seramik", name: "Seramik & Porselen", world: "karo", description: "Yer ve duvar karoları, büyük ebat porselenler, dış mekân ve havuz serileri.", order: 1, texture: "calacatta-oro" },
  { slug: "porselen-karo", name: "Porselen Karo", world: "karo", description: "Yüksek dayanımlı, rektifiyeli yer ve duvar porselenleri.", parent: "seramik", order: 1, texture: "statuario-grey" },
  { slug: "duvar-karosu", name: "Duvar Karosu", world: "karo", description: "Banyo ve mutfak duvarları için sırlı karolar.", parent: "seramik", order: 2, texture: "zellige-blanc" },
  { slug: "dis-mekan-havuz", name: "Dış Mekân & Havuz", world: "karo", description: "Kaymaz, dona dayanıklı teras, bahçe ve havuz karoları.", parent: "seramik", order: 3, texture: "bodrum-stone" },

  { slug: "vitrifiye", name: "Vitrifiye", world: "banyo", description: "Klozet, lavabo, pisuvar ve rezervuarlar.", order: 2, icon: "klozet" },
  { slug: "klozet", name: "Klozet", world: "banyo", description: "Asma ve yere oturan klozetler.", parent: "vitrifiye", order: 1, icon: "klozet" },
  { slug: "lavabo", name: "Lavabo", world: "banyo", description: "Tezgâh üstü, etajerli ve asma lavabolar.", parent: "vitrifiye", order: 2, icon: "lavabo" },

  { slug: "banyo-mobilyasi", name: "Banyo Mobilyası", world: "banyo", description: "Lavabo dolapları, boy dolapları ve aynalar.", order: 3, icon: "dolap" },
  { slug: "armatur", name: "Armatür & Duş", world: "banyo", description: "Bataryalar, duş sistemleri ve ankastre çözümler.", order: 4, icon: "dus" },
  { slug: "aksesuar", name: "Banyo Aksesuarları", world: "banyo", description: "Havluluk, askı, kâğıtlık ve tamamlayıcı ürünler.", order: 5, icon: "aksesuar" },
  { slug: "yapi-kimyasallari", name: "Yapı Kimyasalları", world: "yapi", description: "Seramik yapıştırıcı, derz dolgu ve su yalıtımı.", order: 6, icon: "torba" },
];

export const collections: Collection[] = [
  {
    slug: "calacatta-viola",
    name: "Calacatta Viola",
    look: "mermer",
    tagline: "Seravit'in imzası: ametist damarlı beyaz mermer.",
    story:
      "İtalyan Calacatta ocaklarının en nadir tonlarından ilham alan Viola; beyaz zeminde dolaşan ametist ve altın damarlarıyla banyoya sessiz bir lüks katar. Büyük ebatları sayesinde derzi az, etkisi büyük yüzeyler oluşturur.",
    texture: "calacatta-viola",
  },
  {
    slug: "calacatta-oro",
    name: "Calacatta Oro",
    look: "mermer",
    tagline: "Altın damarlı klasik.",
    story: "Sıcak beyaz zemin üzerinde gri ve altın damarlar. Salon, banyo ve ticari alanlarda zamansız bir seçim.",
    texture: "calacatta-oro",
  },
  {
    slug: "nero-marquina",
    name: "Nero Marquina",
    look: "mermer",
    tagline: "Derin siyah, beyaz damar.",
    story: "Güçlü kontrastıyla duş nişleri, tezgâh arkaları ve vurgu duvarları için dramatik bir yüzey.",
    texture: "nero-marquina",
  },
  {
    slug: "statuario",
    name: "Statuario",
    look: "mermer",
    tagline: "Gri damarlı saf beyaz.",
    story: "Belirgin gri damarlarıyla modern ve ferah mekânlar için.",
    texture: "statuario-grey",
  },
  {
    slug: "travertino",
    name: "Travertino",
    look: "dogal-tas",
    tagline: "Ege evlerinin doğal dokusu.",
    story:
      "Bodrum'un taş evlerini hatırlatan katmanlı traverten dokusu. Mat yüzeyi iç mekândan yarı açık alanlara kesintisiz bir sıcaklık taşır; güneşte parlamaz, yazın serin kalır.",
    texture: "travertino-beige",
  },
  {
    slug: "bodrum-stone",
    name: "Bodrum Stone",
    look: "dogal-tas",
    tagline: "Havuz başı ve teraslar için.",
    story: "20 mm kalınlıkta, R11 kaymaz ve dona dayanıklı. Çim ve çakıl üzerine de uygulanabilir.",
    texture: "bodrum-stone",
  },
  {
    slug: "urban",
    name: "Urban",
    look: "beton",
    tagline: "Endüstriyel sadelik.",
    story: "İnce taneli beton dokusu; gri ve antrasit tonlarıyla loft ve modern projeler için.",
    texture: "beton-grey",
  },
  {
    slug: "mese",
    name: "Meşe",
    look: "ahsap",
    tagline: "Ahşabın sıcaklığı, porselenin dayanımı.",
    story: "Doğal meşe görünümlü parke ebadında porselen; banyoda ve terasta bile kullanılabilir.",
    texture: "mese-dogal",
  },
  {
    slug: "zellige",
    name: "Zellige",
    look: "dekor",
    tagline: "El yapımı görünüm.",
    story: "Işıkla canlanan dalgalı sır; mutfak tezgâh arası ve banyo duvarları için.",
    texture: "zellige-blanc",
  },
  {
    slug: "terrazzo",
    name: "Terrazzo",
    look: "dekor",
    tagline: "Renkli agrega, neşeli zemin.",
    story: "Klasik mozaik betonun porselen yorumu.",
    texture: "terrazzo-krem",
  },
  {
    slug: "aegean",
    name: "Aegean",
    look: "mozaik",
    tagline: "Ege mavisi havuz mozaiği.",
    story: "Cam mozaik, file arkalı paneller; havuz içi ve duş zeminleri için.",
    texture: "aegean-mozaik",
  },
];

const tileTiers: WholesaleTier[] = [
  { minQty: 100, discountPct: 8 },
  { minQty: 500, discountPct: 15 },
];
const unitTiers: WholesaleTier[] = [
  { minQty: 10, discountPct: 6 },
  { minQty: 30, discountPct: 12 },
];

type TileInput = Omit<Product, "unit" | "brand" | "images" | "stock" | "inShowroom" | "tags" | "specs" | "usage" | "features"> &
  Partial<Pick<Product, "stock" | "inShowroom" | "tags" | "specs" | "usage" | "features">>;

/** Karo ürünleri için ortak alanları dolduran yardımcı */
function tile(p: TileInput): Product {
  const specs: Record<string, string> = {
    Ebat: p.size ? `${p.size} cm` : "—",
    ...(p.thickness && { Kalınlık: p.thickness }),
    ...(p.surface && { Yüzey: p.surface[0].toUpperCase() + p.surface.slice(1) }),
    ...(p.packPieces && p.packSize && { Kutu: `${p.packPieces} adet / ${p.packSize.toLocaleString("tr-TR")} m²` }),
    ...(p.palletM2 && { Palet: `${p.palletM2.toLocaleString("tr-TR")} m²` }),
    ...p.specs,
  };
  return {
    brand: "Seravit Seçkisi",
    images: [],
    unit: "m2",
    wholesaleTiers: tileTiers,
    stock: "stokta",
    inShowroom: true,
    tags: [],
    usage: ["ic-mekan"],
    features: ["porselen", "rektifiye", "yer", "duvar"],
    ...p,
    specs,
  };
}

export const products: Product[] = [
  tile({
    slug: "calacatta-viola-60x120-parlak",
    sku: "SRV-CV-60120P",
    name: "Calacatta Viola 60×120 Parlak",
    category: "porselen-karo",
    collection: "calacatta-viola",
    summary: "Ametist ve altın damarlı, parlak yüzeyli büyük ebat porselen.",
    description: "Beyaz zemin üzerinde ametist tonlu damarlar ve ince altın çizgiler. Rektifiyeli kenarları sayesinde neredeyse derzsiz uygulanır; banyo duvarları ve salon zeminleri için.",
    texture: "calacatta-viola",
    look: "mermer",
    surface: "parlak",
    size: "60×120",
    colorName: "Viola",
    colorHex: "#efe9ee",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 2,
    palletM2: 46.08,
    retailPrice: 1390,
    featured: true,
    usage: ["banyo", "ic-mekan"],
    tags: ["mermer", "mor", "lüks"],
  }),
  tile({
    slug: "calacatta-viola-80x160-lappato",
    sku: "SRV-CV-80160L",
    name: "Calacatta Viola 80×160 Lappato",
    category: "porselen-karo",
    collection: "calacatta-viola",
    summary: "Yarı parlak lappato yüzeyde Viola damarları, XL ebat.",
    description: "Lappato yüzey, parlaklığı yumuşatarak damarların derinliğini ortaya çıkarır. 80×160 ebat geniş mekânlarda kesintisiz bir mermer etkisi sağlar.",
    texture: "calacatta-viola",
    look: "mermer",
    surface: "lappato",
    size: "80×160",
    colorName: "Viola",
    colorHex: "#efe9ee",
    thickness: "9 mm",
    packSize: 2.56,
    packPieces: 2,
    palletM2: 40.96,
    retailPrice: 1790,
    stock: "siparis",
    usage: ["banyo", "ic-mekan"],
  }),
  tile({
    slug: "calacatta-oro-60x120-parlak",
    sku: "SRV-CO-60120P",
    name: "Calacatta Oro 60×120 Parlak",
    category: "porselen-karo",
    collection: "calacatta-oro",
    summary: "Altın damarlı, parlak yüzeyli rektifiyeli porselen.",
    description: "Calacatta mermer görünümlü, rektifiyeli kenarlı büyük ebat porselen karo. Salon, banyo ve ticari alanlar için uygundur.",
    texture: "calacatta-oro",
    look: "mermer",
    surface: "parlak",
    size: "60×120",
    colorName: "Oro",
    colorHex: "#f1ede5",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 2,
    palletM2: 46.08,
    retailPrice: 1190,
    featured: true,
    usage: ["banyo", "ic-mekan", "mutfak"],
  }),
  tile({
    slug: "calacatta-oro-60x60-mat",
    sku: "SRV-CO-6060M",
    name: "Calacatta Oro 60×60 Mat",
    category: "porselen-karo",
    collection: "calacatta-oro",
    summary: "Kaymaya karşı güvenli mat yüzeyde Calacatta Oro.",
    description: "Mat yüzeyiyle banyo zeminleri ve yoğun kullanılan alanlar için Calacatta Oro yorumu.",
    texture: "calacatta-oro",
    look: "mermer",
    surface: "mat",
    size: "60×60",
    colorName: "Oro",
    colorHex: "#f1ede5",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 4,
    palletM2: 57.6,
    retailPrice: 890,
    usage: ["banyo", "ic-mekan", "mutfak"],
  }),
  tile({
    slug: "nero-marquina-60x120-parlak",
    sku: "SRV-NM-60120P",
    name: "Nero Marquina 60×120 Parlak",
    category: "porselen-karo",
    collection: "nero-marquina",
    summary: "Derin siyah zemin, keskin beyaz damarlar.",
    description: "Duş nişleri, vurgu duvarları ve tezgâh arkaları için dramatik bir mermer yorumu.",
    texture: "nero-marquina",
    look: "mermer",
    surface: "parlak",
    size: "60×120",
    colorName: "Nero",
    colorHex: "#161416",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 2,
    palletM2: 46.08,
    retailPrice: 1290,
    featured: true,
    usage: ["banyo", "ic-mekan"],
  }),
  tile({
    slug: "statuario-grey-60x120-mat",
    sku: "SRV-ST-60120M",
    name: "Statuario Grey 60×120 Mat",
    category: "porselen-karo",
    collection: "statuario",
    summary: "Gri damarlı beyaz mermer, mat yüzey.",
    description: "Belirgin gri damarlarıyla ferah ve modern mekânlar için.",
    texture: "statuario-grey",
    look: "mermer",
    surface: "mat",
    size: "60×120",
    colorName: "Grey",
    colorHex: "#e3e1de",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 2,
    palletM2: 46.08,
    retailPrice: 990,
    inShowroom: false,
    usage: ["ic-mekan", "banyo"],
  }),
  tile({
    slug: "travertino-beige-60x60-mat",
    sku: "SRV-TR-6060M",
    name: "Travertino Beige 60×60 Mat",
    category: "porselen-karo",
    collection: "travertino",
    summary: "Ege evlerine yakışan doğal traverten dokusu.",
    description: "Traverten taş etkili mat porselen. İç ve yarı açık mekânlarda sıcak bir zemin sunar.",
    texture: "travertino-beige",
    look: "dogal-tas",
    surface: "mat",
    size: "60×60",
    colorName: "Beige",
    colorHex: "#d8c6a8",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 4,
    palletM2: 57.6,
    retailPrice: 690,
    featured: true,
    usage: ["ic-mekan", "banyo", "mutfak"],
  }),
  tile({
    slug: "travertino-beige-60x120-mat",
    sku: "SRV-TR-60120M",
    name: "Travertino Beige 60×120 Mat",
    category: "porselen-karo",
    collection: "travertino",
    summary: "Büyük ebatta traverten; daha az derz, daha sakin yüzey.",
    description: "60×120 ebadıyla geniş salonlar ve yarı açık teraslar için traverten görünümlü porselen.",
    texture: "travertino-beige",
    look: "dogal-tas",
    surface: "mat",
    size: "60×120",
    colorName: "Beige",
    colorHex: "#d8c6a8",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 2,
    palletM2: 46.08,
    retailPrice: 840,
    usage: ["ic-mekan", "dis-mekan"],
  }),
  tile({
    slug: "bodrum-stone-60x60-r11",
    sku: "SRV-BS-6060K",
    name: "Bodrum Stone 60×60 R11 · 20 mm",
    category: "dis-mekan-havuz",
    collection: "bodrum-stone",
    summary: "Kaymaz R11, 20 mm; havuz başı ve teraslar için.",
    description: "Doğal taş görünümlü, R11 kaymazlık sınıfında dış mekân porseleni. Donmaya ve klora dayanıklı; çim, çakıl ya da kum yatağı üzerine kuru uygulanabilir.",
    texture: "bodrum-stone",
    look: "dogal-tas",
    surface: "kaymaz",
    size: "60×60",
    colorName: "Stone",
    colorHex: "#c6bfb2",
    thickness: "20 mm",
    packSize: 0.72,
    packPieces: 2,
    palletM2: 28.8,
    retailPrice: 820,
    featured: true,
    usage: ["dis-mekan", "havuz"],
    features: ["porselen", "rektifiye", "yer", "dis-mekan", "don", "kaymaz"],
    tags: ["havuz", "teras", "kaymaz"],
  }),
  tile({
    slug: "urban-grey-60x60-mat",
    sku: "SRV-UR-6060G",
    name: "Urban Grey 60×60 Mat",
    category: "porselen-karo",
    collection: "urban",
    summary: "İnce taneli açık gri beton dokusu.",
    description: "Endüstriyel görünümlü beton efektli porselen; ofis, mağaza ve modern konutlar için.",
    texture: "beton-grey",
    look: "beton",
    surface: "mat",
    size: "60×60",
    colorName: "Grey",
    colorHex: "#b3b0ab",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 4,
    palletM2: 57.6,
    retailPrice: 590,
    usage: ["ic-mekan", "mutfak"],
  }),
  tile({
    slug: "urban-antrasit-60x60-mat",
    sku: "SRV-UR-6060A",
    name: "Urban Antrasit 60×60 Mat",
    category: "porselen-karo",
    collection: "urban",
    summary: "Koyu antrasit beton dokusu.",
    description: "Urban serisinin koyu tonu; açık gri ile karolaj ya da vurgu alanlarında.",
    texture: "antrasit",
    look: "beton",
    surface: "mat",
    size: "60×60",
    colorName: "Antrasit",
    colorHex: "#3b3a3c",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 4,
    palletM2: 57.6,
    retailPrice: 590,
    inShowroom: false,
    usage: ["ic-mekan", "banyo"],
  }),
  tile({
    slug: "mese-dogal-20x120-mat",
    sku: "SRV-MS-20120M",
    name: "Meşe Doğal 20×120 Mat",
    category: "porselen-karo",
    collection: "mese",
    summary: "Parke ebadında doğal meşe görünümlü porselen.",
    description: "Ahşabın sıcaklığını suya ve çizilmeye dayanıklı porselenle birleştirir. Balıksırtı ya da düz döşenebilir.",
    texture: "mese-dogal",
    look: "ahsap",
    surface: "mat",
    size: "20×120",
    colorName: "Doğal",
    colorHex: "#c09a6c",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 6,
    palletM2: 51.84,
    retailPrice: 760,
    usage: ["ic-mekan", "banyo", "dis-mekan"],
  }),
  tile({
    slug: "zellige-blanc-10x10",
    sku: "SRV-ZL-1010B",
    name: "Zellige Blanc 10×10",
    category: "duvar-karosu",
    collection: "zellige",
    summary: "El yapımı görünümlü, dalgalı sırlı duvar karosu.",
    description: "Fas zellige etkili, ışıkla canlanan dalgalı sır. Mutfak tezgâh arası ve banyo duvarları için.",
    texture: "zellige-blanc",
    look: "dekor",
    surface: "sirli",
    size: "10×10",
    colorName: "Blanc",
    colorHex: "#ebe6da",
    packSize: 0.5,
    packPieces: 50,
    retailPrice: 1450,
    wholesaleTiers: [{ minQty: 50, discountPct: 7 }, { minQty: 200, discountPct: 12 }],
    stock: "sinirli",
    usage: ["mutfak", "banyo"],
    features: ["duvar", "ic-mekan"],
  }),
  tile({
    slug: "terrazzo-krem-60x60",
    sku: "SRV-TZ-6060K",
    name: "Terrazzo Krem 60×60",
    category: "porselen-karo",
    collection: "terrazzo",
    summary: "Renkli agregalı klasik terrazzo görünümü.",
    description: "Krem zemin üzerinde toprak tonlu agregalar; kafe, mağaza ve konut zeminleri için.",
    texture: "terrazzo-krem",
    look: "dekor",
    surface: "mat",
    size: "60×60",
    colorName: "Krem",
    colorHex: "#e9e1d4",
    thickness: "9 mm",
    packSize: 1.44,
    packPieces: 4,
    retailPrice: 720,
    usage: ["ic-mekan", "mutfak"],
  }),
  tile({
    slug: "mat-beyaz-30x60",
    sku: "SRV-DZ-3060B",
    name: "Düz Mat Beyaz 30×60",
    category: "duvar-karosu",
    collection: undefined,
    summary: "Sade, mat beyaz duvar karosu.",
    description: "Her projeye uyan temel beyaz duvar karosu. Dikey veya yatay uygulanabilir.",
    texture: "mat-beyaz",
    look: "duz",
    surface: "mat",
    size: "30×60",
    colorName: "Beyaz",
    colorHex: "#f1efeb",
    packSize: 1.44,
    packPieces: 8,
    retailPrice: 390,
    usage: ["banyo", "mutfak"],
    features: ["duvar", "ic-mekan"],
  }),
  tile({
    slug: "aegean-blue-mozaik",
    sku: "SRV-AG-MZ25",
    name: "Aegean Blue Havuz Mozaiği",
    category: "dis-mekan-havuz",
    collection: "aegean",
    summary: "Cam mozaik, file arkalı, havuz içi kaplama.",
    description: "Ege mavisi tonlarında cam mozaik. File arkalı 30×30 paneller hızlı uygulama sağlar.",
    texture: "aegean-mozaik",
    look: "mozaik",
    surface: "parlak",
    size: "2,5×2,5",
    colorName: "Aegean",
    colorHex: "#2b86b7",
    packSize: 2,
    packPieces: 22,
    stock: "siparis",
    inShowroom: false,
    usage: ["havuz", "banyo"],
    features: ["duvar", "yer", "dis-mekan", "don"],
    specs: { Panel: "30×30 cm", Malzeme: "Cam" },
  }),

  /* ——— Banyo ——— */
  {
    slug: "rimless-asma-klozet",
    sku: "SRV-VT-0001",
    name: "Rimless Asma Klozet",
    brand: "Seravit Seçkisi",
    category: "klozet",
    summary: "Kanalsız hijyenik yıkama, yavaş kapanan kapak.",
    description: "Rimless teknolojili asma klozet. Kolay temizlenir, soft-close kapak dahildir.",
    images: [],
    icon: "klozet",
    unit: "adet",
    retailPrice: 7890,
    wholesaleTiers: unitTiers,
    stock: "stokta",
    inShowroom: true,
    featured: true,
    usage: ["banyo"],
    features: ["rimless", "soft-close"],
    specs: { Ölçü: "36×53 cm", Montaj: "Asma", Kapak: "Soft-close dahil", Yıkama: "Rimless" },
    tags: ["asma klozet", "rimless"],
  },
  {
    slug: "oval-tezgah-ustu-lavabo",
    sku: "SRV-VT-0002",
    name: "Oval Tezgâh Üstü Lavabo 55 cm",
    brand: "Seravit Seçkisi",
    category: "lavabo",
    summary: "İnce kenarlı, mat beyaz çanak lavabo.",
    description: "İnce kenar tasarımlı oval çanak lavabo. Mat beyaz yüzey.",
    images: [],
    icon: "lavabo",
    unit: "adet",
    retailPrice: 3450,
    wholesaleTiers: unitTiers,
    stock: "stokta",
    inShowroom: true,
    featured: true,
    usage: ["banyo"],
    features: [],
    specs: { Ölçü: "55×38 cm", Renk: "Mat beyaz", Montaj: "Tezgâh üstü" },
    tags: ["lavabo", "çanak"],
  },
  {
    slug: "lavabo-dolabi-80-mese",
    sku: "SRV-BM-0001",
    name: "Lavabo Dolabı 80 cm Meşe",
    brand: "Seravit Seçkisi",
    category: "banyo-mobilyasi",
    summary: "Asma, çift çekmeceli, meşe kaplama.",
    description: "Çift çekmeceli asma lavabo dolabı; ayna ve lavabo ile takım olarak sunulur.",
    images: [],
    icon: "dolap",
    unit: "takim",
    retailPrice: 18900,
    stock: "siparis",
    inShowroom: true,
    usage: ["banyo"],
    features: [],
    specs: { Genişlik: "80 cm", Malzeme: "Meşe kaplama", Set: "Dolap + lavabo + ayna" },
    tags: ["banyo dolabı", "meşe"],
  },
  {
    slug: "ankastre-dus-seti-siyah",
    sku: "SRV-AR-0001",
    name: "Ankastre Termostatik Duş Seti — Mat Siyah",
    brand: "Seravit Seçkisi",
    category: "armatur",
    summary: "30 cm tepe duşu, el duşu ve termostatik gövde.",
    description: "Termostatik ankastre duş sistemi. 30 cm yağmur başlık, el duşu ve gömme gövde dahil.",
    images: [],
    icon: "dus",
    unit: "takim",
    retailPrice: 14500,
    wholesaleTiers: [{ minQty: 5, discountPct: 5 }, { minQty: 20, discountPct: 10 }],
    stock: "stokta",
    inShowroom: true,
    featured: true,
    usage: ["banyo"],
    features: ["termostatik"],
    specs: { Renk: "Mat siyah", Başlık: "30 cm", Kontrol: "Termostatik" },
    tags: ["duş seti", "siyah", "ankastre"],
  },
  {
    slug: "lavabo-bataryasi-altin",
    sku: "SRV-AR-0002",
    name: "Lavabo Bataryası — Fırçalanmış Altın",
    brand: "Seravit Seçkisi",
    category: "armatur",
    summary: "Tek kumandalı, seramik kartuşlu, PVD kaplama.",
    description: "Fırçalanmış altın PVD kaplamalı, tek kumandalı lavabo bataryası.",
    images: [],
    icon: "batarya",
    unit: "adet",
    retailPrice: 4290,
    stock: "sinirli",
    inShowroom: true,
    usage: ["banyo"],
    features: ["pvd"],
    specs: { Kaplama: "PVD fırçalanmış altın", Kartuş: "35 mm seramik" },
    tags: ["batarya", "altın"],
  },
  {
    slug: "aksesuar-seti-4lu",
    sku: "SRV-AK-0001",
    name: "Banyo Aksesuar Seti (4'lü)",
    brand: "Seravit Seçkisi",
    category: "aksesuar",
    summary: "Havluluk, kâğıtlık, askı ve fırçalık.",
    description: "Paslanmaz çelik gövdeli dört parçalı aksesuar seti.",
    images: [],
    icon: "aksesuar",
    unit: "takim",
    retailPrice: 2350,
    stock: "stokta",
    inShowroom: false,
    usage: ["banyo"],
    features: [],
    specs: { Malzeme: "Paslanmaz çelik", Parça: "4" },
    tags: ["aksesuar"],
  },
  {
    slug: "flex-seramik-yapistirici-25kg",
    sku: "SRV-YK-0001",
    name: "Flex Seramik Yapıştırıcı 25 kg",
    brand: "Seravit Seçkisi",
    category: "yapi-kimyasallari",
    summary: "C2TE S1, büyük ebat ve dış mekân uyumlu.",
    description: "Esnek, kayma direnci yüksek çimento esaslı yapıştırıcı. Porselen ve büyük ebat karolar için.",
    images: [],
    icon: "torba",
    unit: "paket",
    retailPrice: 420,
    wholesaleTiers: [{ minQty: 40, discountPct: 8 }, { minQty: 200, discountPct: 15 }],
    stock: "stokta",
    inShowroom: false,
    usage: [],
    features: [],
    specs: { Sınıf: "C2TE S1", Ambalaj: "25 kg torba" },
    tags: ["yapıştırıcı"],
  },
  {
    slug: "derz-dolgu-5kg",
    sku: "SRV-YK-0002",
    name: "Su İtici Derz Dolgu 5 kg",
    brand: "Seravit Seçkisi",
    category: "yapi-kimyasallari",
    summary: "CG2WA, 1–8 mm derzler için, 12 renk.",
    description: "Su itici, küf önleyici katkılı çimento esaslı derz dolgu.",
    images: [],
    icon: "torba",
    unit: "paket",
    retailPrice: 180,
    wholesaleTiers: [{ minQty: 50, discountPct: 8 }, { minQty: 200, discountPct: 15 }],
    stock: "stokta",
    inShowroom: false,
    usage: [],
    features: [],
    specs: { Sınıf: "CG2WA", Ambalaj: "5 kg", "Derz aralığı": "1–8 mm" },
    tags: ["derz"],
  },
];
